name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm install

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}
          SPONSORKIT_AFDIAN_EXECHANGERATE: ${{ secrets.SPONSORKIT_AFDIAN_EXECHANGERATE }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
